./run_local.sh: line 48: python: command not found
